/**
 * Branded statement PDFs (server-only). Renders a GetCalmly-headed A4 document
 * with a summary strip and a paginated table, using the real brand mark. Amounts
 * are written as "Rs" (the standard PDF fonts can't encode the ₹ glyph).
 */
import { readFile } from 'fs/promises'
import path from 'path'
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFImage } from 'pdf-lib'

export const rs = (n: number) => 'Rs ' + Math.round(n).toLocaleString('en-IN')

const INK = rgb(0.11, 0.17, 0.23) // #1C2B3A
const MUTED = rgb(0.42, 0.48, 0.55)
const LINE = rgb(0.88, 0.90, 0.92)
const CORAL = rgb(0.78, 0.33, 0.24)

const A4: [number, number] = [595.28, 841.89]
const MARGIN = 48

export type StatementTable = { headers: string[]; rows: (string | number)[][]; align?: ('left' | 'right')[] }

let brandCache: Uint8Array | null = null
async function brandMark(): Promise<Uint8Array> {
  if (!brandCache) brandCache = new Uint8Array(await readFile(path.join(process.cwd(), 'public/brand/logo-mark.png')))
  return brandCache
}

export async function buildStatementPdf(opts: {
  title: string
  subtitle?: string
  meta?: string[]
  summary?: { label: string; value: string }[]
  table: StatementTable
}): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const logo = await doc.embedPng(await brandMark())

  const contentW = A4[0] - MARGIN * 2
  const cols = opts.table.headers.length
  const colW = contentW / cols
  const align = opts.table.align ?? opts.table.headers.map((_, i) => (i === cols - 1 ? 'right' : 'left'))

  let page = doc.addPage(A4)
  let y = A4[1] - MARGIN

  const text = (s: string, x: number, yy: number, f: PDFFont, size: number, color = INK) => page.drawText(s, { x, y: yy, size, font: f, color })
  const clip = (s: string, f: PDFFont, size: number, maxW: number) => {
    if (f.widthOfTextAtSize(s, size) <= maxW) return s
    let out = s
    while (out.length > 1 && f.widthOfTextAtSize(out + '…', size) > maxW) out = out.slice(0, -1)
    return out + '…'
  }

  function header(img: PDFImage) {
    const h = 30
    const w = (img.width / img.height) * h
    page.drawImage(img, { x: MARGIN, y: y - h, width: w, height: h })
    text(opts.title, MARGIN, y - h - 26, bold, 18)
    let cursor = y - h - 26 - 16
    for (const line of [opts.subtitle, ...(opts.meta ?? [])].filter(Boolean) as string[]) {
      text(line, MARGIN, cursor, font, 10, MUTED)
      cursor -= 14
    }
    page.drawText('getcalmly.com', { x: A4[0] - MARGIN - font.widthOfTextAtSize('getcalmly.com', 10), y: y - 12, size: 10, font, color: MUTED })
    y = cursor - 12
  }

  function summaryStrip(items: { label: string; value: string }[]) {
    if (items.length === 0) return
    const boxH = 46
    const boxW = contentW / items.length
    page.drawRectangle({ x: MARGIN, y: y - boxH, width: contentW, height: boxH, color: rgb(0.97, 0.97, 0.99) })
    items.forEach((it, i) => {
      const x = MARGIN + boxW * i + 12
      text(it.label.toUpperCase(), x, y - 16, font, 7.5, MUTED)
      text(it.value, x, y - 34, bold, 14)
    })
    y -= boxH + 22
  }

  function tableHeader() {
    text('' , MARGIN, y, font, 9) // no-op to keep y semantics
    opts.table.headers.forEach((h, i) => {
      const cellX = MARGIN + colW * i
      const s = clip(h.toUpperCase(), bold, 8, colW - 8)
      const w = bold.widthOfTextAtSize(s, 8)
      text(s, align[i] === 'right' ? cellX + colW - 6 - w : cellX + 4, y, bold, 8, MUTED)
    })
    y -= 8
    page.drawLine({ start: { x: MARGIN, y }, end: { x: MARGIN + contentW, y }, thickness: 1, color: LINE })
    y -= 16
  }

  function ensureRoom(rowH: number) {
    if (y - rowH > MARGIN + 30) return
    // Footer page number, then a fresh page.
    const n = doc.getPageCount()
    page.drawText(`Page ${n}`, { x: A4[0] / 2 - 12, y: MARGIN - 16, size: 8, font, color: MUTED })
    page = doc.addPage(A4)
    y = A4[1] - MARGIN
    tableHeader()
  }

  header(logo)
  summaryStrip(opts.summary ?? [])
  tableHeader()

  for (const row of opts.table.rows) {
    ensureRoom(20)
    row.forEach((cell, i) => {
      const cellX = MARGIN + colW * i
      const s = clip(String(cell), font, 9, colW - 8)
      const w = font.widthOfTextAtSize(s, 9)
      text(s, align[i] === 'right' ? cellX + colW - 6 - w : cellX + 4, y, font, 9)
    })
    y -= 8
    page.drawLine({ start: { x: MARGIN, y: y + 2 }, end: { x: MARGIN + contentW, y: y + 2 }, thickness: 0.5, color: LINE })
    y -= 12
  }

  // Final footer.
  text('Generated by GetCalmly · this statement is system-produced and needs no signature.', MARGIN, MARGIN - 16, font, 8, MUTED)
  page.drawText(`Page ${doc.getPageCount()}`, { x: A4[0] - MARGIN - 40, y: MARGIN - 16, size: 8, font, color: MUTED })
  void CORAL

  return doc.save()
}

/** A Response that downloads as a .pdf file. */
export function pdfResponse(filename: string, bytes: Uint8Array): Response {
  return new Response(bytes as unknown as BodyInit, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control': 'no-store',
    },
  })
}
